# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4ee827a8080c8f15a54cc33fa51c42f5e0e096854910eb08e92807f87e3fc18b82056ce36dcb220a6cc3217cff71339879869d2ae14cec669b4932d04cfe8f6

test:
  secret_key_base: 9facd709a4867d554ce3cc476cfc06200e8ef909931cc39fa0ad311f7fc2ad6f920c353c3158dbafca5cb1c9b1c12d0a848bbbf941f6eb9c3410467c4135acf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
